name: Go Backend CI
on:
  push:
    branches: 
      - feature/actions

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: movies
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Install dependencies
      working-directory: go-app
      run: go mod download

    - name: Build
      working-directory: go-app
      run: go build -v ./...

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./go-app
        push: true
        tags: gaetancarre/goflix_backend_v0.0.1:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          docker pull gaetancarre/goflix_backend_v0.0.1:latest
          docker stop goflix_backend || true
          docker rm goflix_backend || true
          docker run -d -p 8080:8080 --name goflix_backend gaetancarre/goflix_backend_v0.0.1:latest