name: React Frontend CI/CD

on:
  push:
    branches:
      - feature/actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: react-app
        run: npm install

      - name: Build
        working-directory: react-app
        run: npm run build

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./react-app
          file: ./react-app/Dockerfile
          push: true
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
