name: React Frontend CI/CD

on:
  push:
    branches:
      - feature/actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: react-app
        run: npm install

      - name: Build
        working-directory: react-app
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./react-app
          push: true
          tags: gaetancarre/goflix_frontend_v0.0.1:latest